### ISSUE TITLE
linux vnext emulator makes a new certificate everytime I run it

### ISSUE THREAD

**Issue by derek-ko** [Azure/azure-cosmos-db-emulator-docker#129]
**Describe the bug**
linux vnext emulator makes a new certificate everytime I run it.

**To Reproduce**
1. docker run --detach --publish 8081:8081 --publish 1234:1234 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview --protocol https
2. openssl s_client -connect localhost:8081 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ./cosmos-emulator.crt
3. Check if the certificate has changed from before.

**Expected behavior**
Always use the same certificate when running the emulator.

**Desktop (please complete the following information):**
 - OS: macOS M1
 - Browser: chrome
 - Version: 131.0.6778.86 (arm64)

**Docker Images Used:**
 - Linux

**Arguments && Environment variables to start Docker:**
docker run --detach --publish 8081:8081 --publish 1234:1234 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview --protocol https
 
**Docker Environment**
 - Rancher Desktop 1.15.1

**Comment by alaye-ms** [comment]
Hello! 

The vnext emulator creates a new certificate every time it's run by design at this time. For your use case you might want to provide your own certificate when running the emulator, thus ensuring it's the same every time. You can do that with the following steps:

Create your own certificate, for now we use the PFX format, or pull a cert from an existing run from the emulator.

Then you pass in the cert with 

`docker run --detach --publish 8081:8081 --publish 1234:1234 --mount type=bind,source=./cert/path/on/local,target=/cert/path/on/container mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview --protocol https --cert-path /cert/path/on/container`

**Comment by derek-ko** [comment]
OK, I`ll use this way. Thank you.
