### ISSUE TITLE
Be able to use custom certificate

### ISSUE THREAD

**Issue by SteveLowe** [Azure/azure-cosmos-db-emulator-docker#46]
It would be easier to use the CosmosDB emulator docker image for local development if we could specify a custom certificate to use, instead of having to install the generated one into the local certificate store (and re-install it when it changes).

In our case, we would like to be able to use https://github.com/FiloSottile/mkcert to generate a locally trusted ca, then issue a cert for CosmosDB to use.

I notice that you can use a custom certificate using `AZURE_COSMOS_EMULATOR_CERTIFICATE`. Unfortunately from testing it looks like the emulator will only work if its a self signed certificate issued by localhost.

For some context, we run the emulator in docker-compose (using the linux image) for local development. Our developers use a mix of Linux, Mac and Windows. Automating the import of the certificate across all 3 platforms took a lot longer than it would have with mkcert, and requires root/admin.

**Comment by milismsft** [comment]
@SteveLowe regarding the Linux image, there's already an option set via an environment variable (see "-e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true") which will preserve the emulator's certificate from being regenerated each time the container starts.

We do not support custom certificates to be used by the emulator at this time. Main reason for this limitation is the extra fields that need to be present within the certificate which are specific to the exact environment the emulator is running. One possible option you can try to implement locally is:
-  configure the network setting on your Docker compose/Dockerfile for the emulator's container to use a rather fixed IP address
- create/start the emulator's container with the data persistency option set to true (in addition to all the other options) and optionally mount a host machine folder to be used for copying over the emulator's certificate.
- use docker exec to access the emulator's container and copy the .PFX file which is the emulator's certificate
- next time you create a new container you can add one extra step which is to add/copy this certificate file into the emulator's container at the exact same location.

This certificate file can be used for as long as the IP address of the container remains the same. If the host's IP address is subject to changes, use the container's fixed IP address for the emulator's endpoint in your app environment or "localhost" but in this case please configure the SDK clients to "gateway mode" rather than default.

You can also try to generate/clone a similar certificate on the side, but it's not something I will recommend since you must account for every field in the certificate that the emulator depends on.

**Comment by ivarprudnikov** [comment]
There is another alternative - switch off the certificate check for the emulator client. The example below is for a Go sdk, but similar http client options ought to be available in other languages:

```go
package test

import (
    "context"
    "crypto/tls"
    "net/http"

    "github.com/Azure/azure-sdk-for-go/sdk/azcore"
    "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
    "github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos"
)
// skip self signed emulator cert check
func emulatorClientOpts() *azcosmos.ClientOptions {
    client := &http.Client{
        Transport: &http.Transport{
            TLSClientConfig: &tls.Config{
                InsecureSkipVerify: true,
            },
        },
    }

    return &azcosmos.ClientOptions{
        ClientOptions: azcore.ClientOptions{
            Transport: client,
        },
        EnableContentResponseOnWrite: true,
    }
}

serviceUrl := "https://localhost:8081"
emulatorAccountKey := "xxxxxxxx"

cred, err := azcosmos.NewKeyCredential(emulatorAccountKey)
handleError(err)
serviceClient, err := azcosmos.NewClientWithKey(opts.ServiceUrl, cred, emulatorClientOpts())
handleError(err)
// then try and read from db
dbClient, err := serviceClient.NewDatabase("testdb")
handleError(err)
resp, err := dbClient.Read(context.Background(), nil)
handleError(err)

func handleError(err error) {
    if err != nil {
        panic(err)
    }
}
```

**Comment by mrkdrd** [comment]
@ivarprudnikov 
I see your alternatives works for GOlang, do you know how to use this "fix" when using the Java client? I do not see where I can configure the HTTP Client and its SSL settings when initializing the CosmosClient via its builder :/ 

Currently I am stuck since my setup requires Docker in Docker where the CosmosDbEmulator is run.

**Comment by ivarprudnikov** [comment]
Java SDK seems to use Netty https://github.com/Azure/azure-sdk-for-java/blob/e9f7f65f47ca17dea3cd161e0b71135cbbebf1b4/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/Configs.java#L123

I would follow the path to configuring the system properties that SSL provider recognizes https://netty.io/4.1/api/io/netty/handler/ssl/SslContext.html#defaultClientProvider--

something like `-Djdk.internal.httpclient.disableHostnameVerification`

**Comment by mrkdrd** [comment]
Thanks @ivarprudnikov, this was something that I also thought of (configuring the client via properties) but could not find the matching property. Unfortunately I still get the error: **"No subject alternative DNS name matching dind found.** :(
I tried multiple approaches setting the property and also confirmed that the property is correctly set.

After setting a breakpoint at the point where the property is evaluated, inside the package: jdk.internal.net.http.common it is not stopping. Therefore I assume the property has no effect.
